version: '3.8'

services:
  database:
    container_name: sn-compose-database
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=social_network_db
      - MYSQL_TCP_PORT=3306
    ports:
      - "3306:3306"
    build: ./database
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
      
  backend:
    container_name: sn-compose-backend
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=compose
    build: ./backend
    depends_on:
      database:
        condition: service_healthy
        
  frontend:
    container_name: sn-compose-frontend
    environment:
      - VITE_REST_SERVER_URL=http://localhost:3000
      - VITE_SOCKET_SERVER_URL=http://localhost:3003
    ports:
      - 5173:80
    build: ./frontend
    
  io:
    container_name: sn-io
    environment:
      - NODE_ENV=compose
      - CORS_ORIGIN=http://localhost:5173
    ports:
      - 3003:3003
    build: ./io
    
  localstack:
    container_name: sn-localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    image: localstack/localstack